config {
  type: "test",
  dataset: {name: "all_posts_table", schema: "outputs"},
}

-- Couldn't find a way to use schema and table name as input reference i.e. ${ref({schema: "intermediate", name: "questions"})}
-- so, instead I am matching the table 'ref' exactly as in all_posts_table as they must be the same
input "questions" {
  SELECT 73210679 AS post_id, '2022-08-02 16:16:31.810000 UTC' AS created_at, 'question' AS type, 'question_1' AS title, 'help_1' AS body, 11226740 AS owner_user_id, NULL AS parent_id UNION ALL
  SELECT 73284406 AS post_id, '2022-08-08 21:53:16.703000 UTC' AS created_at, 'question' AS type, 'question_2' AS title, 'help_2' AS body, 19123691 AS owner_user_id, NULL AS parent_id UNION ALL
  SELECT 73250763 AS post_id, '2022-08-05 13:43:25.850000 UTC' AS created_at, 'question' AS type, 'question_3' AS title, 'help_3' AS body, 17654458 AS owner_user_id, NULL AS parent_id UNION ALL
  SELECT 73406942 AS post_id, '2022-08-18 17:05:12.950000 UTC' AS created_at, 'question' AS type, 'question_4' AS title, 'help_4' AS body, 897007 AS owner_user_id, NULL AS parent_id UNION ALL
  SELECT 73200968 AS post_id, '2022-08-02 01:00:36.200000 UTC' AS created_at, 'question' AS type, 'question_5' AS title, 'help_5' AS body, 19502695 AS owner_user_id, NULL AS parent_id
}

input "answers" {
  SELECT 73248720 AS post_id, '2022-08-05 11:02:18.823000 UTC' AS created_at, 'answer' AS type, CAST(NULL AS STRING) AS title, 'answer_1' AS body, 7410178 AS owner_user_id, 72830182 AS parent_id UNION ALL
  SELECT 73248721 AS post_id, '2022-08-05 11:02:21.603000 UTC' AS created_at, 'answer' AS type, CAST(NULL AS STRING) AS title, 'answer_2' AS body, 19595490 AS owner_user_id, 73248560 AS parent_id UNION ALL
  SELECT 73248723 AS post_id, '2022-08-05 11:02:25.203000 UTC' AS created_at, 'answer' AS type, CAST(NULL AS STRING) AS title, 'answer_3' AS body, 16786025 AS owner_user_id, 73248264 AS parent_id UNION ALL
  SELECT 73248738 AS post_id, '2022-08-05 11:03:32.090000 UTC' AS created_at, 'answer' AS type, CAST(NULL AS STRING) AS title, 'answer_4' AS body, 11085251 AS owner_user_id, 73237008 AS parent_id UNION ALL
  SELECT 73248739 AS post_id, '2022-08-05 11:03:43.880000 UTC' AS created_at, 'answer' AS type, CAST(NULL AS STRING) AS title, 'answer_5' AS body, 2049476 AS owner_user_id, 67918503 AS parent_id
}


SELECT 73210679 AS post_id, '2022-08-02 16:16:31.810000 UTC' AS created_at, 'question' AS type, 'question_1' AS title, 'help_1' AS body, 11226740 AS owner_user_id, NULL AS parent_id UNION ALL
SELECT 73284406 AS post_id, '2022-08-08 21:53:16.703000 UTC' AS created_at, 'question' AS type, 'question_2' AS title, 'help_2' AS body, 19123691 AS owner_user_id, NULL AS parent_id UNION ALL
SELECT 73250763 AS post_id, '2022-08-05 13:43:25.850000 UTC' AS created_at, 'question' AS type, 'question_3' AS title, 'help_3' AS body, 17654458 AS owner_user_id, NULL AS parent_id UNION ALL
SELECT 73406942 AS post_id, '2022-08-18 17:05:12.950000 UTC' AS created_at, 'question' AS type, 'question_4' AS title, 'help_4' AS body, 897007 AS owner_user_id, NULL AS parent_id UNION ALL
SELECT 73200968 AS post_id, '2022-08-02 01:00:36.200000 UTC' AS created_at, 'question' AS type, 'question_5' AS title, 'help_5' AS body, 19502695 AS owner_user_id, NULL AS parent_id UNION ALL
SELECT 73248720 AS post_id, '2022-08-05 11:02:18.823000 UTC' AS created_at, 'answer' AS type, NULL AS title, 'answer_1' AS body, 7410178 AS owner_user_id, 72830182 AS parent_id UNION ALL
SELECT 73248721 AS post_id, '2022-08-05 11:02:21.603000 UTC' AS created_at, 'answer' AS type, NULL AS title, 'answer_2' AS body, 19595490 AS owner_user_id, 73248560 AS parent_id UNION ALL
SELECT 73248723 AS post_id, '2022-08-05 11:02:25.203000 UTC' AS created_at, 'answer' AS type, NULL AS title, 'answer_3' AS body, 16786025 AS owner_user_id, 73248264 AS parent_id UNION ALL
SELECT 73248738 AS post_id, '2022-08-05 11:03:32.090000 UTC' AS created_at, 'answer' AS type, NULL AS title, 'answer_4' AS body, 11085251 AS owner_user_id, 73237008 AS parent_id UNION ALL
SELECT 73248739 AS post_id, '2022-08-05 11:03:43.880000 UTC' AS created_at, 'answer' AS type, NULL AS title, 'answer_5' AS body, 2049476 AS owner_user_id, 67918503 AS parent_id